import Introduction from '@src/Container/Page/Introduction';
import type { NextPage } from 'next';
import Head from 'next/head';

const IntroductionPage: NextPage = () => (
  <>
    <Head>
      <title>DayCare</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Introduction />
  </>
);

export default IntroductionPage;
