/* eslint-disable import/prefer-default-export */
export const city = {
  서울특별시: [
    '종로구',
    '중구',
    '용산구',
    '성동구',
    '광진구',
    '동대문구',
    '중랑구',
    '성북구',
    '강북구',
    '도봉구',
    '노원구',
    '은평구',
    '서대문구',
    '마포구',
    '양천구',
    '강서구',
    '구로구',
    '금천구',
    '영등포구',
    '동작구',
    '관악구',
    '서초구',
    '강남구',
    '송파구',
    '강동구',
  ],
  부산광역시: [
    '중구',
    '서구',
    '동구',
    '영도구',
    '부산진구',
    '동래구',
    '남구',
    '북구',
    '해운대구',
    '사하구',
    '금정구',
    '강서구',
    '연제구',
    '수영구',
    '사상구',
    '기장군',
  ],
  대구광역시: [
    '중구',
    '동구',
    '서구',
    '남구',
    '북구',
    '수성구',
    '달서구',
    '달성군',
  ],
  인천광역시: [
    '중구',
    '동구',
    '미추홀구',
    '연수구',
    '남동구',
    '부평구',
    '계양구',
    '서구',
    '강화군',
    '옹진군',
  ],
  광주광역시: ['동구', '서구', '남구', '북구', '광산구'],
  대전광역시: ['동구', '중구', '서구', '유성구', '대덕구'],
  울산광역시: ['중구', '남구', '동구', '북구', '울주군'],
  세종특별자치시: ['세종특별자치시'],
  경기도: [
    '수원시 장안구',
    '수원시 권선구',
    '수원시 팔달구',
    '수원시 영통구',
    '성남시 수정구',
    '성남시 중원구',
    '성남시 분당구',
    '의정부시',
    '안양시 만안구',
    '안양시 동안구',
    '부천시',
    '광명시',
    '평택시',
    '동두천시',
    '안산시 상록구',
    '안산시 단원구',
    '고양시 덕양구',
    '고양시 일산동구',
    '고양시 일산서구',
    '과천시',
    '구리시',
    '남양주시',
    '오산시',
    '시흥시',
    '군포시',
    '의왕시',
    '하남시',
    '용인시 처인구',
    '용인시 기흥구',
    '용인시 수지구',
    '파주시',
    '이천시',
    '안성시',
    '김포시',
    '화성시',
    '광주시',
    '양주시',
    '포천시',
    '여주시',
    '연천군',
    '가평군',
    '양평군',
  ],
  강원도: [
    '춘천시',
    '원주시',
    '강릉시',
    '동해시',
    '태백시',
    '속초시',
    '삼척시',
    '홍천군',
    '횡성군',
    '영월군',
    '평창군',
    '정선군',
    '철원군',
    '화천군',
    '양구군',
    '인제군',
    '고성군',
    '양양군',
  ],
  충청북도: [
    '청주시 상당구',
    '청주시 서원구',
    '청주시 흥덕구',
    '청주시 청원구',
    '충주시',
    '제천시',
    '보은군',
    '옥천군',
    '영동군',
    '증평군',
    '진천군',
    '괴산군',
    '음성군',
    '단양군',
  ],
  충청남도: [
    '천안시 동남구',
    '천안시 서북구',
    '공주시',
    '보령시',
    '아산시',
    '서산시',
    '논산시',
    '계룡시',
    '당진시',
    '금산군',
    '부여군',
    '서천군',
    '청양군',
    '홍성군',
    '예산군',
    '태안군',
  ],
  전라북도: [
    '전주시 완산구',
    '전주시 덕진구',
    '군산시',
    '익산시',
    '정읍시',
    '남원시',
    '김제시',
    '완주군',
    '진안군',
    '무주군',
    '장수군',
    '임실군',
    '순창군',
    '고창군',
    '부안군',
  ],
  전라남도: [
    '목포시',
    '여수시',
    '순천시',
    '나주시',
    '광양시',
    '담양군',
    '곡성군',
    '구례군',
    '고흥군',
    '보성군',
    '화순군',
    '장흥군',
    '강진군',
    '해남군',
    '영암군',
    '무안군',
    '함평군',
    '영광군',
    '장성군',
    '완도군',
    '진도군',
    '신안군',
  ],
  경상북도: [
    '포항시 남구',
    '포항시 북구',
    '경주시',
    '김천시',
    '안동시',
    '구미시',
    '영주시',
    '영천시',
    '상주시',
    '문경시',
    '경산시',
    '군위군',
    '의성군',
    '청송군',
    '영양군',
    '영덕군',
    '청도군',
    '고령군',
    '성주군',
    '칠곡군',
    '예천군',
    '봉화군',
    '울진군',
    '울릉군',
  ],
  경상남도: [
    '창원시 의창구',
    '창원시 성산구',
    '창원시마산합포구',
    '창원시마산회원구',
    '창원시 진해구',
    '진주시',
    '통영시',
    '사천시',
    '김해시',
    '밀양시',
    '거제시',
    '양산시',
    '의령군',
    '함안군',
    '창녕군',
    '고성군',
    '남해군',
    '하동군',
    '산청군',
    '함양군',
    '거창군',
    '합천군',
  ],
  제주특별자치도: ['제주시', '서귀포시'],
};

export const changeFilterData = (value: string) => {
  switch (value) {
    case '일반':
      return 'property_normal';
    case '영아전담':
      return 'property_infants';
    case '장애아전담':
      return 'property_impaired';
    case '장애아통합':
      return 'property_impaired_combine';
    case '방과후전담':
      return 'property_after';
    case '방과후통합':
      return 'property_after_combine';
    case '시간연장':
      return 'property_time_extension';
    case '휴일보육':
      return 'property_holiday';
    case '24시간':
      return 'property_allday';
    case '0세':
      return 'child_count_age0';
    case '1세':
      return 'child_count_age1';
    case '2세':
      return 'child_count_age2';
    case '3세':
      return 'child_count_age3';
    case '4세':
      return 'child_count_age4';
    case '5세':
      return 'child_count_age5';
    case '보육교사':
      return 'employee_count_nursery';
    case '특수교사':
      return 'employee_count_special';
    case '치료교사':
      return 'employee_count_cure';
    case '영양사':
      return 'employee_count_nutritionist';
    case '간호사':
      return 'employee_count_nurse';
    case '간호조무사':
      return 'employee_count_nursingassistant';
    default:
      return '';
  }
};

export const dummyCenter = {
  abolition_date: null,
  accreditation: '',
  address_detail: '서울특별시 서초구 청계산로11길 7-12 708동 1층',
  address_number: '06802',
  authorization_date: '2013-09-30T15:00:00.000Z',
  cctv_count: 0,
  certification: null,
  characteristics: '',
  child_count: 0,
  child_count_age0: 0,
  child_count_age1: 0,
  child_count_age2: 0,
  child_count_age3: 0,
  child_count_age4: 0,
  child_count_age5: 0,
  child_count_age6: 0,
  child_count_age7: 0,
  city: '서울특별시',
  city_detail: '서초구',
  city_dong: '',
  city_scale: '',
  class_count: 0,
  class_count0: 0,
  class_count1: 0,
  class_count2: 0,
  class_count3: 0,
  class_count4: 0,
  class_count5: 0,
  class_count_mix2: 0,
  class_count_mix5: 0,
  class_count_special: 0,
  code: '',
  consignment_name: '',
  consignment_status: '',
  consignment_type: '',
  director_name: '',
  employee_count: 0,
  employee_count0: 0,
  employee_count1: 0,
  employee_count2: 0,
  employee_count4: 0,
  employee_count6: 0,
  employee_count_cook: 0,
  employee_count_cure: 0,
  employee_count_director: 0,
  employee_count_nurse: 0,
  employee_count_nursery: 0,
  employee_count_nursingassistant: 0,
  employee_count_nutritionist: 0,
  employee_count_officeworker: 0,
  employee_count_other: 0,
  employee_count_special: 0,
  fax: '02-572-2030',
  homepage: 'http://cafe.naver.com/foresta7',
  id: 4458,
  impaired_after_child_count: 0,
  impaired_after_count: 0,
  impaired_allday_child_count: 0,
  impaired_allday_count: 0,
  impaired_child_count: 0,
  impaired_extension_child_count: 0,
  impaired_holiday_child_count: 0,
  infant_child_count: 0,
  insurance_compensation: null,
  insurance_detriment: null,
  insurance_fire: null,
  lat: '37.44401897798263',
  lon: '127.06217099875766',
  name: '서초구립 포레스타7단지어린이집',
  normal_after_child_count: 0,
  normal_child_count_age0: 0,
  normal_child_count_age1: 0,
  normal_child_count_age2: 0,
  normal_child_count_age3: 0,
  normal_child_count_age4: 0,
  normal_child_count_mix01: 0,
  normal_child_count_mix12: 0,
  normal_child_count_mix23: 0,
  normal_child_count_mix34: 0,
  normal_holiday_child_count: 0,
  nuri_impaired_count: 0,
  nursery_count: '4',
  nursery_roomarea: '197',
  operation_status: '정상',
  playground_count: 0,
  property_after: '',
  property_after_combine: '',
  property_allday: '',
  property_holiday: '',
  property_impaired: '',
  property_impaired_combine: '',
  property_infants: '',
  property_normal: '',
  property_time_extension: '',
  representative_name: '',
  rest_end_date: null,
  rest_start_date: null,
  school_vehicle: '미운영',
  server_date: '2022-07-08 10:48:35',
  service: '',
  student_count: 26,
  student_max: 42,
  support: '',
  teaching_staff_count: 9,
  tel: '070-7204-2030',
  type: '국공립',
  isLike: false,
};
